services:
  nginx:
    image: nginx:latest
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "8080:8080"
    networks:
      fbtravi_net:
networks:
  fbtravi_net:
    name: fbtravi_net