version: "3"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./mount_point:/etc/prometheus
    networks:
      prometheus_net:
networks:
  prometheus_net:
    name: prometheus_net
