
version: "3"

services:
  web:
    image: nginx:latest
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
     - ./index.html:/etc/nginx/html/index.html
    ports:
     - "8080:8080"
    networks:
      fbtravi_net:
networks:
  fbtravi_net:
    name: fbtravi_net